package co.edu.unal.hermes.modelo.alertasAutomaticas;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;

import co.edu.unal.hermes.utils.UtilPalabraClave;

/**
 * HerAval generated by MyEclipse Persistence Tools
 */

public class AlertasAutomaticasAval implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long aviId;
	private String investigador;
	private String tituloProyecto;
	private String emailInvestigador;
		
	public AlertasAutomaticasAval() {
	    super();
	    // TODO Auto-generated constructor stub
    }
	
	public Long getAviId() {
		return aviId;
	}
	public void setAviId(Long aviId) {
		this.aviId = aviId;
	}
	public String getInvestigador() {
		return investigador;
	}
	public void setInvestigador(String investigador) {
		this.investigador = investigador;
	}
	public String getEmailInvestigador() {
		return emailInvestigador;
	}
	public void setEmailInvestigador(String emailInvestigador) {
		this.emailInvestigador = emailInvestigador;
	}

	public String getTituloProyecto() {
		return tituloProyecto;
	}

	public void setTituloProyecto(String tituloProyecto) {
		this.tituloProyecto = tituloProyecto;
	}

}