package co.edu.unal.hermes.modelo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;

import co.edu.unal.hermes.utils.UtilPalabraClave;

/**
 * HerAval generated by MyEclipse Persistence Tools
 */

public class Aval implements java.io.Serializable {

	/**
	 * Tipos de aval
	 */

	public static final Long DOMINIO_TIPO_AVAL = 81L;

	public static final String TIPO_INVESTIGACION = "PINV";
	public static final String TIPO_INVESTIGACION_ANTERIOR = "PI";
	public static final String TIPO_REGALIAS = "SR";
	public static final String TIPO_REGALIAS_VERIF_REQ = "VRSR";
	public static final String TIPO_CONVOCATORIA_REGALIAS = "PCR";
	public static final String TIPO_MOVILIDAD = "ME";
	public static final String TIPO_INVESTIGACION_CONT = "PINVC";
	public static final String TIPO_JORNADA_DOCENTE = "JD";
	public static final String TIPO_GRUPO_INVESTIGACION = "GR";
	public static final String TIPO_INVESTIGADOR_INDEPENDIENTE = "INI";
	public static final String TIPO_PAED_REGALIAS = "PSR";
	public static final String TIPO_CENTRO_INVESTIGACION = "CIN";
	public static final String TIPO_ETICO = "ETICO";
	public static final String TIPO_ARTICULO_INVESTIGACION = "ARTINV";

	// Permiso marco
	public static final String TIPO_PERMISO_RECOLECCION = "BI";
	public static final String TIPO_ACCESO_RECURSO = "AR";

	/**
	 * Estados del aval
	 */
	public static final Long DOMINIO_ESTADO_AVAL = 78L;

	public static final String FORMULACION = "P";
	public static final String ENVIADO = "I";
	public static final String DEVUELTO = "C";
	public static final String BORRADO = "B";
	public static final String REVISADO_UAB = "U";
	public static final String REVISADO_FACULTAD = "F";
	public static final String REVISADO_DIRECCION = "D";
	public static final String REVISADO_VICERRECTORIA = "V";
	public static final String APROBADO = "S";
	public static final String NEGADO = "N";
	public static final String ENVIADO_SEDE  = "IS";
	public static final String ENVIADO_FACULTAD  = "IF";
	
	public static final String REVISADO_DRE = "RD";
	public static final String DEVUELTO_DRE = "RDC";
	public static final String REVISADO_RECTORIA = "RR";
	public static final String DEVUELTO_RECTORIA = "RRC";
	
	public static final String ETICO_ENVIADO_CEPI = "EP";
	public static final String ETICO_APROBADO_CEPI = "SP";
	public static final String ETICO_NO_APROBADO_CEPI = "NP";
	public static final String ETICO_DEVUELTO_CEPI = "CP";
	public static final String ETICO_ENVIADO_CESI = "ES";
	public static final String ETICO_APROBADO_CESI = "SS";
	public static final String ETICO_NO_APROBADO_CESI = "NS";
	

	private static final long serialVersionUID = 1L;
	private Long aviId;
	private Dependencia dependencia;
	private String tipoDocumento;
	private String tiempoFormulacionInv;
	private String documento;
	private String tipoDocumentoEst;
	private String documentoEst;
	private String tipo;
	private String evento;
	private String idTutor;
	private String tdoTutor;
	private String otroLaboratorio;

	private Long idProyecto;
	private String nombreProyecto;
	private String tipoEvento;

	private String descripcionfacultad;
	private Date fecha;
	private Date fechaUltimoEnvio;
	private Long aviMontoFinal = 0L;

	private Date fechaInicio;
	private Date fechaFin;
	private String pais;
	private String paisNombre;
	private double duracion = 0L;
	private double duracions = 0L;
	private double duraciond = 0L;
	private double duracionh = 0L;
	private String archivoAval;
	private String aviFrescosUnalAporta = "0";
	private String aviCiudad;
	private String nombreInvestigador;
	private String aviNumeroConvocatoria;
	private String aviNaturalezaConvocatoria;
	private String codigoProyecto;
	private String categoriaConvocatoria;
	private String modalidadLaboratorio;
	private String isocial = "";
	private String estadoCandidato;
	private String grupoCandidato;
	private String comisionEstudios;
	private String programaDoc;
	private String telefonoMovil;
	private String correoElectronico;
	private String uab;
	private Long avalRelacionado;

	private String areaInvestigacion;
	private String lineaInvestigacion;

	private String modalidadDoc;
	private String porcentajeDoc;
	private TipoPonencia ponencia;

	// REQ 26 Miguel Cubides
	private Long aviVrTotal = 0L;
	private Long aviMontoEntConv = 0L;
	private Long aviHorasDoc = 0L;
	private String aviTextoCompCoor;
	private String textoVicerrectoria;
	private String aviIp = "";

	private Date aviFechaAvalUab;
	private Date aviFechaAvalFac;
	private Date aviFechaAvalCoor;
	private Date aviFechaAvalVice;
	private Date aviFechaCierreConv;

	private Set<ArchivoAval> archivosCoor = new HashSet<ArchivoAval>();
	
	// Fin REQ 26 Miguel Cubides

	private String aviEstado;
	private String aviAvalUab;
	private String aviAvalfacultad;
	private String aviAvaldireccion;
	private String comentariosUab;
	private String aviTitulo = "";
	private String aviEntidad;
	private Long aviMontosolicitado = 0L;
	private String aviConvocatoria;
	private String aviEntidadejecutora = "UNIVERSIDAD NACIONAL DE COLOMBIA";
	private String aviEntidadcoejecutora;
	private Long aviHorasprincipal = 0L;
	private Long aviHorascoinvestigador = 0L;
	private Long aviEspecieunal = 0L;
	private Long aviEspecieotros = 0L;
	private Long aviFrescosunal = 0L;
	private Long aviFrescosotros = 0L;
	private Integer aviModalidad = 0;
	private String nombreFacultad;
	private String resumen = "";
	private String palabraClave;
	private String region;
	private String subRegion;
	private String lugarEjecucion = "";
	private String fase;
	private String tipoPropuesta;
	private String entidades;
	private String montosEntidConv;
	private String avalVice;
	private Long valorPersonalTotal;

	private String objetivoPrincipal = "";
	private String areaCiencia;
	private String objetivoSocioeconomico;
	private String serviciosAcademicos = "NO";
	private Long semanasFormulacion = 0L;
	private Long horasSemanaFormulacion = 0L;
	private Long semanasFormulacionInv = 0L;
	private Long horasSemanaFormulacionInv = 0L;
	private Long horasInvestigador = 0L;
	private String reqContrapartidas = "NO";
	private String poblacionVulnerable;
	private String razonVulnerabilidad = "";
	private String financiacion;
	private String tipoEntidad;
	private String departamento;

	private String costoPersona;
	private String iniciativaInterna;
	private String siIniciativaInterna;
	private String noIniciativaInterna;
	private String modalidad;
	private String mecanismo;
	private String categoriaGPI;
	private String subCategoriaGPI;
	private Date aviFechaPublicacionResult;
	private String tecnologia;
	private String descripcionTecnologia;
	private String estadoDesarrollo;
	private String sustitutos;
	private String perfilesClientes;
	private String aliados;
	private String creadorId;
	private String creadorDocumento;

	private Long noExpediente;

	// INICIO AVAL MOVILIDADES
	private String participanteMovilidad;
	private String tituloTrabajoMovilidad;
	private String institucionMovilidad;
	private String institucionCoorgMovilidad;
	private String lugarMovilidad;
	private String duracionMovilidad;
	private String tematicaFRedes;
	private String aportaRecursosPropios;

	private Set<ResultadoAval> resultados = new HashSet<ResultadoAval>();
	// FIN AVAL MOVILIDADES

	private String consideracionesEticas;

	private Set<ArchivoAval> archivos = new HashSet<ArchivoAval>();
	private Set<CoinvestigadorAval> coinvestigador = new HashSet<CoinvestigadorAval>();
	private Set<EntidadArticulo> entidadAval = new HashSet<EntidadArticulo>();
	private Set<PalabraClave> palabrasClaves = new HashSet<PalabraClave>();
	private Set<Dependencia> dependencias = new HashSet<Dependencia>();
	private Set<MontoAno> montoAval = new HashSet<MontoAno>();
	private Set<PoblacionSolidaria> poblacionAval = new HashSet<PoblacionSolidaria>();
	private Set<AvalActividad> actividadAval = new HashSet<AvalActividad>();

	private Long montoEntidadCoejecutora;
	private Long montoEspecieEntidadCoejecutora;
	private String nombreGrupoPINV;

	private String responsableCambio = "";
	private String modalidadPropiedadIntelectual;
	private Convenio convenio;
	private String interSedes;
	private String dependenciaContrapartida; // Para el caso de aval de Proyecto
												// de Investigacion - contrapartida
												// F: Solicitud a la facultad D:
												// Solicitud a la direccion
	private Long terminos;
	// Requerimiento #2218 - Angela Devia
	private Boolean avalVigente;
	private String tieneArchivosSoporteParticipacionConvocatoria;
	private String tieneConvocatoriaProyecto;
	private String entidadTerritorialProyectoRegalidas;
	private String esAvalParaRevisionSede;
	private String esAvalParaRevisionVice;
	
	// Requerimiento #4026 - Miguel Cantor L.
	private String tipoAvalCIN;
	
	private String esAvalParaRevisionDRE;
	private String avalDRE;
	private String textoDRE;
	private Date fechaAvalDRE;
	
	private String avalRectoria;
	private String textoRectoria;
	private Date fechaAvalRectoria;

	
	//CEPI Y CESI
	private AvalComiteEtica cepi;
	
	private String avalCEPI;
	private String textoCEPI;
	private Date fechaAvalCEPI;
	
	private String avalTieneRecurso;
	private String textoRecurso;
	private Tipos tipoRecursoAvalEtico;
	private Date fechaRecurso;
	
	private String avalCEPIRecurso;
	private Date fechaAvalCEPIRecurso;
	
	private String avalCESI;
	private String textoCESI;
	private Date fechaAvalCESI;
	
	private String avalTieneQueja;
	private String textoQueja;
	private Date fechaQueja;
	
	private String avalCESIQueja;
	private String textoCESIQueja;
	private Date fechaCESIQueja;
	
	// ARTICULO INVESTIGACION
	private String avalArticuloTitulo;
	private Tipos avalArticuloEstado;
	private String avalArticuloResumen;
	private String avalArticuloRevista;
	private String avalArticuloObjetivo;
	
	//Requerimiento tipo especificación aval
	private Set<AvalSubTipos> subTipoEspecificaciones = new HashSet<AvalSubTipos>();
	
	private String codigoMinciencias;

	// Constructors

	/** default constructor */
	public Aval() {
		/**
		 * Constructor por defecto de la clase aval
		 */
	}

	/** minimal constructor */
	public Aval(Long aviId) {
		this.aviId = aviId;
	}

	public String getCodigoProyecto() {
		return codigoProyecto;
	}

	public void setCodigoProyecto(String codigoProyecto) {
		this.codigoProyecto = codigoProyecto;
	}

	public String getAviFrescosUnalAporta() {
		return aviFrescosUnalAporta;
	}

	public void setAviFrescosUnalAporta(String aviFrescosUnalAporta) {
		this.aviFrescosUnalAporta = aviFrescosUnalAporta;
	}

	public String getAviCiudad() {
		return aviCiudad;
	}

	public void setAviCiudad(String aviCiudad) {
		this.aviCiudad = aviCiudad;
	}

	public Date getFecha() {
		return fecha;
	}

	public String getDescripcionfacultad() {
		return descripcionfacultad;
	}

	public void setDescripcionfacultad(String descripcionfacultad) {
		this.descripcionfacultad = descripcionfacultad;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTipoDocumentoEst() {
		return tipoDocumentoEst;
	}

	public void setTipoDocumentoEst(String tipoDocumentoEst) {
		this.tipoDocumentoEst = tipoDocumentoEst;
	}

	public String getDocumentoEst() {
		return documentoEst;
	}

	public void setDocumentoEst(String documentoEst) {
		this.documentoEst = documentoEst;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getEvento() {
		return evento;
	}

	public void setEvento(String evento) {
		this.evento = evento;
	}

	public Set<ArchivoAval> getArchivos() {
		return archivos;
	}

	public void setArchivo(ArchivoAval archivo) {
		archivos.add(archivo);
	}

	public void setCoinvestigador(CoinvestigadorAval persona) {
		persona.setAval(this);
		coinvestigador.add(persona);
	}

	public void eliminarArchivo(ArchivoAval archivo) {
		archivos.remove(archivo);
	}

	public void eliminarCoinvestigador(CoinvestigadorAval aval) {
		coinvestigador.remove(aval);
	}

	public Set<CoinvestigadorAval> getCoinvestigador() {
		return coinvestigador;
	}

	public void setCoinvestigador(Set<CoinvestigadorAval> coinvestigador) {
		this.coinvestigador = coinvestigador;
	}

	public void setArchivos(Set<ArchivoAval> archivos) {
		this.archivos = archivos;
	}

	public Set<ArchivoAval> getArchivosCoor() {
		return archivosCoor;
	}

	public List<ArchivoAval> getArchivosCoorList() {
		return new LinkedList<ArchivoAval>(archivosCoor);
	}

	public void setArchivosCoor(Set<ArchivoAval> archivosCoor) {
		this.archivosCoor = archivosCoor;
	}

	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getDocumento() {
		return documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Boolean getAvalVigente() {
		return avalVigente;
	}

	public void setAvalVigente(Boolean avalVigente) {
		this.avalVigente = avalVigente;
	}

	public String getNombreEstado() {

		String nombre = "";

		if (FORMULACION.equals(this.aviEstado)) {
			nombre = "Formulación";
		} else if (DEVUELTO.equals(this.aviEstado)) {
			nombre = "Devuelto para correcciones";
		} else if (ENVIADO.equals(this.aviEstado)) {
			nombre = "Enviado";
		} else if (BORRADO.equals(this.aviEstado)) {
			nombre = "Solicitud anulada";
		} else if (REVISADO_UAB.equals(this.aviEstado)) {

			nombre = verificarEstadoUab();

		} else if (REVISADO_FACULTAD.equals(this.aviEstado) && APROBADO.equals(this.aviAvalfacultad)
				&& this.tipo.equals(TIPO_JORNADA_DOCENTE) && this.aviAvalUab == null) {
			nombre = "Aprobado en UAB";
		} else if (REVISADO_FACULTAD.equals(this.aviEstado)) {
			nombre = verificarEstadoFacultad();
		} else if (REVISADO_DIRECCION.equals(this.aviEstado)) {
			nombre = verificarEstadoDireccion();
		}else if (ENVIADO_FACULTAD.equals(this.aviEstado)) {
			nombre = "Enviado a facultad";
		}else if (ENVIADO_SEDE.equals(this.aviEstado)) {
			nombre = "Enviado a la sede";
		}else if (REVISADO_VICERRECTORIA.equals(this.aviEstado)) {
			if (avalVice != null && avalVice.equals(APROBADO)) {
				nombre = "Aprobado en Vicerrectoría";
			} else {
				nombre = "No aprobado en Vicerrectoría";
			}
		} else if (REVISADO_DRE.equals(this.aviEstado)) {
			nombre = verificarEstadoDRE();
		} else if (REVISADO_RECTORIA.equals(this.aviEstado)) {
			nombre = verificarEstadoRectoria();
		} else if (ETICO_ENVIADO_CEPI.equals(this.aviEstado)) {
			nombre = "Enviado a CEPI";
		} else if (ETICO_APROBADO_CEPI.equals(this.aviEstado)) {
			nombre = "Aprobado CEPI";
		} else if (ETICO_NO_APROBADO_CEPI.equals(this.aviEstado)) {
			nombre = "No aprobado CEPI";
		} else if (ETICO_DEVUELTO_CEPI.equals(this.aviEstado)) {
			nombre = "Devuelto para correcciones CEPI";
		} else if (ETICO_ENVIADO_CESI.equals(this.aviEstado)) {
			nombre = "Enviado a CESI";
		} else if (ETICO_APROBADO_CESI.equals(this.aviEstado)) {
			nombre = "Aprobado CESI";
		} else if (ETICO_NO_APROBADO_CESI.equals(this.aviEstado)) {
			nombre = "No aprobado CESI";
		}
		
		return nombre;
	}

	private String verificarEstadoUab() {
		String nombreEstadoUab = "Revisado";
		if (aviAvalUab != null && aviAvalUab.equals(APROBADO) && aviAvalfacultad == null && aviAvaldireccion == null) {
			nombreEstadoUab = "Aprobado en UAB";
		} else if (aviAvalUab != null && aviAvalUab.equals(APROBADO) && aviAvalfacultad != null
				&& aviAvalfacultad.equals(APROBADO)) {
			nombreEstadoUab = "Aprobado en UAB - Asignado coordinador en Vicedecanatura";
		} else if (aviAvalUab != null && aviAvalUab.equals(NEGADO)) {
			nombreEstadoUab = "No aprobado en UAB";
		} else if (aviAvalUab != null && aviAvalUab.equals(APROBADO) && aviAvaldireccion != null
				&& aviAvaldireccion.equals(APROBADO)) {
			nombreEstadoUab = "Aprobado en UAB - Asignado coordinador en Dirección";
		}
		return nombreEstadoUab;
	}

	private String verificarEstadoFacultad() {
		String nombreEstadoFacultad = "";
		if ((this.tipo.equals(TIPO_INVESTIGACION_CONT) && this.getDependenciaContrapartida() != null
				&& "D".equals(this.getDependenciaContrapartida()))
				|| (this.dependencia != null && this.dependencia.getId() != null
						&& (this.getDependencia().getId().startsWith("6")
								|| this.getDependencia().getId().startsWith("7")
								|| this.getDependencia().getId().startsWith("8")))) {
			nombreEstadoFacultad = "Enviado";
		} else {
			if (!this.tipo.equals(TIPO_INVESTIGACION_CONT)) {
				if (aviAvalfacultad != null && aviAvalfacultad.equals(APROBADO)) {
					nombreEstadoFacultad = "Aprobado en Facultad/Instituto";
				} else if (aviAvalfacultad != null && aviAvalfacultad.equals(NEGADO)) {
					nombreEstadoFacultad = "No aprobado en Facultad/Instituto";
				} else {
					nombreEstadoFacultad = "Revisado Facultad/Instituto";
				}
			} else if (this.tipo.equals(TIPO_PERMISO_RECOLECCION) || this.tipo.equals(TIPO_ACCESO_RECURSO)) {

				if (aviAvalfacultad != null && aviAvalfacultad.equals(APROBADO)) {
					nombreEstadoFacultad = "Aprobado por coordinador";
				} else if (aviAvalfacultad != null && aviAvalfacultad.equals(NEGADO)) {
					nombreEstadoFacultad = "No aprobado por coordinador";
				} else {
					nombreEstadoFacultad = "Revisado coordinador";
				}
			}
		}
		return nombreEstadoFacultad;
	}

	private String verificarEstadoDireccion() {

		if (aviAvaldireccion != null && aviAvaldireccion.equals(APROBADO)) {
			return "Aprobado en Dirección";
		} else if (aviAvaldireccion != null && aviAvaldireccion.equals(NEGADO)) {
			return "No aprobado en Dirección";
		} else {
			return "Revisado Dirección";
		}
	}
	
	private String verificarEstadoDRE() {

		if (avalDRE != null && avalDRE.equals(APROBADO)) {
			return "Aprobado en Dirección de Relaciones Exteriores";
		} else if (avalDRE != null && avalDRE.equals(NEGADO)) {
			return "No Aprobado en Dirección de Relaciones Exteriores";
		} else {
			return "Revisado en Dirección de Relaciones Exteriores";
		}
	}
	
	private String verificarEstadoRectoria() {
		if (avalRectoria != null && avalRectoria.equals(APROBADO)) {
			return "Aprobado en Rectoría";
		} else {
			return "";
		}
	}

	public String getNombreTipo() {
		String nombre = "";
		if (this.tipo == null) {
			return "";
		}
		if (this.tipo.equals(TIPO_INVESTIGACION) || "PI".equals(this.tipo) || "IP".equals(this.tipo)) {
			nombre = "Proyecto investigación";
		} else if (this.tipo.equals(TIPO_INVESTIGACION_CONT)) {
			nombre = "Proyecto investigación - Contrapartida";
		} else if (this.tipo.equals(TIPO_JORNADA_DOCENTE)) {
			nombre = "Jornada docente";
		} else if (this.tipo.equals(TIPO_REGALIAS)) {
			nombre = "Regalías";
		} else if (this.tipo.equals(TIPO_GRUPO_INVESTIGACION)) {
			nombre = "Grupo de investigación";
		} else if (this.tipo.equals(TIPO_INVESTIGADOR_INDEPENDIENTE)) {
			nombre = "Investigador independiente o Becas doctorales";
		} else if (this.tipo.equals(TIPO_MOVILIDAD)) {
			nombre = "Movilidad / Evento";
		} else if ("JI".equals(this.tipo)) {
			nombre = "Jóvenes investigadores";
		} else if (this.tipo.equals(TIPO_PERMISO_RECOLECCION)) {
			nombre = "Recolección de especímenes";
		} else if (this.tipo.equals(TIPO_ACCESO_RECURSO)) {
			nombre = "Acceso a recurso genético";
		} else if (this.tipo.equals(TIPO_PAED_REGALIAS)) {
			nombre = "PROYECTO - PAED/ Convocatorias FCTeI - Regalías";
		} else if (this.tipo.equals(TIPO_CENTRO_INVESTIGACION)) {
			nombre = "Laboratorios, centros o Institutos de Investigación";
		} else if (this.tipo.equals(TIPO_ETICO)) {
			nombre = "Aval ético para proyecto";
		} else if (this.tipo.equals(TIPO_ARTICULO_INVESTIGACION)) {
			nombre = "Artículo de investigación";
		} else if (this.tipo.equals(TIPO_CONVOCATORIA_REGALIAS)) {
			nombre = "Aval etapa presentación proyectos Convocatorias SGR- Regalías";
		} else if (this.tipo.equals(TIPO_REGALIAS_VERIF_REQ)) {
			nombre = "Aval etapa verificación de requisitos SGR - Regalías";
		}
		return nombre;
	}

	public boolean isEsRequiereTerminos() {
		if (!isEsJornadaDocente() && !isEsProyectoContrapartida()) {
			return true;
		}
		return false;
	}

	public String getNombreFacultad() {
		return nombreFacultad;
	}

	public void setNombreFacultad(String nombreFacultad) {
		this.nombreFacultad = nombreFacultad;
	}

	public Dependencia getDependencia() {
		return dependencia;
	}

	public void setDependencia(Dependencia dependencia) {
		this.dependencia = dependencia;
	}

	public Long getAviId() {
		return this.aviId;
	}

	public void setAviId(Long aviId) {
		this.aviId = aviId;
	}

	public String getAviEstado() {
		if (this.aviEstado != null) {
			return this.aviEstado;
		}
		return "";
	}

	public void setAviEstado(String aviEstado) {
		this.aviEstado = aviEstado;
	}

	public String getAviAvalfacultad() {
		return this.aviAvalfacultad;
	}

	public void setAviAvalfacultad(String aviAvalfacultad) {
		this.aviAvalfacultad = aviAvalfacultad;
	}

	public String getAviAvaldireccion() {
		return this.aviAvaldireccion;
	}

	public void setAviAvaldireccion(String aviAvaldireccion) {
		this.aviAvaldireccion = aviAvaldireccion;
	}

	public String getAviTitulo() {
		return this.aviTitulo;
	}

	public void setAviTitulo(String aviTitulo) {
		this.aviTitulo = aviTitulo;
	}

	public String getAviEntidad() {
		return this.aviEntidad;
	}

	public void setAviEntidad(String aviEntidad) {
		this.aviEntidad = aviEntidad;
	}

	public Long getAviMontosolicitado() {
		return this.aviMontosolicitado;
	}

	public void setAviMontosolicitado(Long aviMontosolicitado) {
		this.aviMontosolicitado = aviMontosolicitado;
	}

	public String getAviConvocatoria() {
		return this.aviConvocatoria;
	}

	public void setAviConvocatoria(String aviConvocatoria) {
		this.aviConvocatoria = aviConvocatoria;
	}

	public String getAviEntidadejecutora() {
		return this.aviEntidadejecutora;
	}

	public void setAviEntidadejecutora(String aviEntidadejecutora) {
		this.aviEntidadejecutora = aviEntidadejecutora;
	}

	public String getAviEntidadcoejecutora() {
		return this.aviEntidadcoejecutora;
	}

	public void setAviEntidadcoejecutora(String aviEntidadcoejecutora) {
		this.aviEntidadcoejecutora = aviEntidadcoejecutora;
	}

	public Long getAviHorasprincipal() {
		return this.aviHorasprincipal;
	}

	public void setAviHorasprincipal(Long aviHorasprincipal) {
		this.aviHorasprincipal = aviHorasprincipal;
	}

	public Long getAviHorascoinvestigador() {
		return this.aviHorascoinvestigador;
	}

	public void setAviHorascoinvestigador(Long aviHorascoinvestigador) {
		this.aviHorascoinvestigador = aviHorascoinvestigador;
	}

	public Long getAviEspecieunal() {
		return this.aviEspecieunal;
	}

	public void setAviEspecieunal(Long aviEspecieunal) {
		this.aviEspecieunal = aviEspecieunal;
	}

	public Long getAviEspecieotros() {
		if (this.aviEspecieotros != null) {
			return this.aviEspecieotros;
		}
		return 0L;
	}

	public void setAviEspecieotros(Long aviEspecieotros) {
		this.aviEspecieotros = aviEspecieotros;
	}

	public Long getAviFrescosunal() {
		return this.aviFrescosunal;
	}

	public void setAviFrescosunal(Long aviFrescosunal) {
		this.aviFrescosunal = aviFrescosunal;
	}

	public Long getAviFrescosotros() {
		return this.aviFrescosotros;
	}

	public void setAviFrescosotros(Long aviFrescosotros) {
		this.aviFrescosotros = aviFrescosotros;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getPais() {
		return pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getPaisNombre() {
		return paisNombre;
	}

	public void setPaisNombre(String paisNombre) {
		this.paisNombre = paisNombre;
	}

	public String getArchivoAval() {
		return archivoAval;
	}

	public void setArchivoAval(String archivoAval) {
		this.archivoAval = archivoAval;
	}

	public boolean isDescargar() {
		if (this.archivoAval != null && this.archivoAval.length() > 0) {
			return true;
		}
		return false;
	}

	public boolean isEditarAval() {
		if (this.aviEstado.equals(FORMULACION) || this.aviEstado.equals(DEVUELTO) || this.aviEstado.equals(ETICO_DEVUELTO_CEPI)) {
			return true;
		}
		return false;
	}

	public TipoPonencia getPonencia() {
		return ponencia;
	}

	public void setPonencia(TipoPonencia ponencia) {
		this.ponencia = ponencia;
	}

	public String getNombreInvestigador() {
		return nombreInvestigador;
	}

	public void setNombreInvestigador(String nombreInvestigador) {
		this.nombreInvestigador = nombreInvestigador;
	}

	public String getAviNumeroConvocatoria() {
		return aviNumeroConvocatoria;
	}

	public void setAviNumeroConvocatoria(String aviNumeroConvocatoria) {
		this.aviNumeroConvocatoria = aviNumeroConvocatoria;
	}

	public Long getAviMontoFinal() {
		return aviMontoFinal;
	}

	public void setAviMontoFinal(Long aviMontoFinal) {
		this.aviMontoFinal = aviMontoFinal;
	}

	public String getEstadoCandidato() {
		return estadoCandidato;
	}

	public void setEstadoCandidato(String estadoCandidato) {
		this.estadoCandidato = estadoCandidato;
	}

	public String getGrupoCandidato() {
		return grupoCandidato;
	}

	public void setGrupoCandidato(String grupoCandidato) {
		this.grupoCandidato = grupoCandidato;
	}

	public String getComisionEstudios() {
		return comisionEstudios;
	}

	public void setComisionEstudios(String comisionEstudios) {
		this.comisionEstudios = comisionEstudios;
	}

	public String getProgramaDoc() {
		return programaDoc;
	}

	public void setProgramaDoc(String programaDoc) {
		this.programaDoc = programaDoc;
	}

	public String getTelefonoMovil() {
		return telefonoMovil;
	}

	public void setTelefonoMovil(String telefonoMovil) {
		this.telefonoMovil = telefonoMovil;
	}

	public String getCorreoElectronico() {
		return correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public String getAreaInvestigacion() {
		return areaInvestigacion;
	}

	public void setAreaInvestigacion(String areaInvestigacion) {
		this.areaInvestigacion = areaInvestigacion;
	}

	public String getLineaInvestigacion() {
		return lineaInvestigacion;
	}

	public void setLineaInvestigacion(String lineaInvestigacion) {
		this.lineaInvestigacion = lineaInvestigacion;
	}

	public String getModalidadDoc() {
		return modalidadDoc;
	}

	public void setModalidadDoc(String modalidadDoc) {
		this.modalidadDoc = modalidadDoc;
	}

	public String getPorcentajeDoc() {
		return porcentajeDoc;
	}

	public void setPorcentajeDoc(String porcentajeDoc) {
		this.porcentajeDoc = porcentajeDoc;
	}

	public Long getAviVrTotal() {
		return aviVrTotal;
	}

	public void setAviVrTotal(Long aviVrTotal) {
		this.aviVrTotal = aviVrTotal;
	}

	public Long getAviMontoEntConv() {
		return aviMontoEntConv;
	}

	public void setAviMontoEntConv(Long aviMontoEntConv) {
		this.aviMontoEntConv = aviMontoEntConv;
	}

	public Long getAviHorasDoc() {
		return aviHorasDoc;
	}

	public void setAviHorasDoc(Long aviHorasDoc) {
		this.aviHorasDoc = aviHorasDoc;
	}

	public String getAviIp() {
		return aviIp;
	}

	public void setAviIp(String aviIp) {
		this.aviIp = aviIp;
	}

	public Date getAviFechaAvalFac() {
		return aviFechaAvalFac;
	}

	public void setAviFechaAvalFac(Date aviFechaAvalFac) {
		this.aviFechaAvalFac = aviFechaAvalFac;
	}

	public Date getAviFechaAvalCoor() {
		return aviFechaAvalCoor;
	}

	public void setAviFechaAvalCoor(Date aviFechaAvalCoor) {
		this.aviFechaAvalCoor = aviFechaAvalCoor;
	}

	public Date getAviFechaCierreConv() {
		return aviFechaCierreConv;
	}

	public void setAviFechaCierreConv(Date aviFechaCierreConv) {
		this.aviFechaCierreConv = aviFechaCierreConv;
		// Requerimiento #2218 - Angela Devia
		try {
			if (aviFechaCierreConv.before(new Date())) {
				this.avalVigente = true;
			} else {
				this.avalVigente = false;
			}
		} catch (Exception e) {
			this.avalVigente = false;
		}
		// Fin Requerimiento #2218 - Angela Devia
	}

	public String getAviTextoCompCoor() {
		return aviTextoCompCoor;
	}

	public void setAviTextoCompCoor(String aviTextoCompCoor) {
		this.aviTextoCompCoor = aviTextoCompCoor;
	}

	public String getIdTutor() {
		return idTutor;
	}

	public void setIdTutor(String idTutor) {
		this.idTutor = idTutor;
	}

	public String getTdoTutor() {
		return tdoTutor;
	}

	public void setTdoTutor(String tdoTutor) {
		this.tdoTutor = tdoTutor;
	}

	public Integer getAviModalidad() {
		return aviModalidad;
	}

	public void setAviModalidad(Integer aviModalidad) {
		this.aviModalidad = aviModalidad;
	}

	public String getResumen() {
		return resumen;
	}

	public void setResumen(String resumen) {
		this.resumen = resumen;
	}

	public String getPalabraClave() {
		return palabraClave;
	}

	public void setPalabraClave(String palabraClave) {
		this.palabraClave = palabraClave;
	}

	public String getLugarEjecucion() {
		return lugarEjecucion;
	}

	public void setLugarEjecucion(String lugarEjecucion) {
		this.lugarEjecucion = lugarEjecucion;
	}

	public String getTipoPropuesta() {
		return tipoPropuesta;
	}

	public void setTipoPropuesta(String tipoPropuesta) {
		this.tipoPropuesta = tipoPropuesta;
	}

	public String getSubRegion() {
		return subRegion;
	}

	public void setSubRegion(String subRegion) {
		this.subRegion = subRegion;
	}

	public String getFase() {
		return fase;
	}

	public void setFase(String fase) {
		this.fase = fase;
	}

	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getEntidades() {
		return entidades;
	}

	public void setEntidades(String entidades) {
		this.entidades = entidades;
	}

	public String getMontosEntidConv() {
		return montosEntidConv;
	}

	public void setMontosEntidConv(String montosEntidConv) {
		this.montosEntidConv = montosEntidConv;
	}

	public String getAvalVice() {
		return avalVice;
	}

	public void setAvalVice(String avalVice) {
		this.avalVice = avalVice;
	}

	public String getObjetivoPrincipal() {
		return objetivoPrincipal;
	}

	public void setObjetivoPrincipal(String objetivoPrincipal) {
		this.objetivoPrincipal = objetivoPrincipal;
	}

	public String getAreaCiencia() {
		return areaCiencia;
	}

	public void setAreaCiencia(String areaCiencia) {
		this.areaCiencia = areaCiencia;
	}

	public String getObjetivoSocioeconomico() {
		return objetivoSocioeconomico;
	}

	public void setObjetivoSocioeconomico(String objetivoSocioeconomico) {
		this.objetivoSocioeconomico = objetivoSocioeconomico;
	}

	public String getServiciosAcademicos() {
		return serviciosAcademicos;
	}

	public void setServiciosAcademicos(String serviciosAcademicos) {
		this.serviciosAcademicos = serviciosAcademicos;
	}

	public Long getSemanasFormulacion() {
		return semanasFormulacion;
	}

	public void setSemanasFormulacion(Long semanasFormulacion) {
		this.semanasFormulacion = semanasFormulacion;
	}

	public Long getHorasSemanaFormulacion() {
		return horasSemanaFormulacion;
	}

	public void setHorasSemanaFormulacion(Long horasSemanaFormulacion) {
		this.horasSemanaFormulacion = horasSemanaFormulacion;
	}

	public Long getSemanasFormulacionInv() {
		return semanasFormulacionInv;
	}

	public void setSemanasFormulacionInv(Long semanasFormulacionInv) {
		this.semanasFormulacionInv = semanasFormulacionInv;
	}

	public Long getHorasSemanaFormulacionInv() {
		return horasSemanaFormulacionInv;
	}

	public void setHorasSemanaFormulacionInv(Long horasSemanaFormulacionInv) {
		this.horasSemanaFormulacionInv = horasSemanaFormulacionInv;
	}

	public Long getHorasInvestigador() {
		return horasInvestigador;
	}

	public void setHorasInvestigador(Long horasInvestigador) {
		this.horasInvestigador = horasInvestigador;
	}

	public String getTiempoFormulacionInv() {
		return tiempoFormulacionInv;
	}

	public void setTiempoFormulacionInv(String tiempoFormulacionInv) {
		this.tiempoFormulacionInv = tiempoFormulacionInv;
	}

	public String getReqContrapartidas() {
		return reqContrapartidas;
	}

	public void setReqContrapartidas(String reqContrapartidas) {
		this.reqContrapartidas = reqContrapartidas;
	}

	public String getPoblacionVulnerable() {
		return poblacionVulnerable;
	}

	public void setPoblacionVulnerable(String poblacionVulnerable) {
		this.poblacionVulnerable = poblacionVulnerable;
	}

	public String getRazonVulnerabilidad() {
		return razonVulnerabilidad;
	}

	public void setRazonVulnerabilidad(String razonVulnerabilidad) {
		this.razonVulnerabilidad = razonVulnerabilidad;
	}

	public String getFinanciacion() {
		return financiacion;
	}

	public void setFinanciacion(String financiacion) {
		this.financiacion = financiacion;
	}

	public String getTipoEntidad() {
		return tipoEntidad;
	}

	public void setTipoEntidad(String tipoEntidad) {
		this.tipoEntidad = tipoEntidad;
	}

	public String getDepartamento() {
		return departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getCostoPersona() {
		return costoPersona;
	}

	public void setCostoPersona(String costoPersona) {
		this.costoPersona = costoPersona;
	}

	public String getIniciativaInterna() {
		return iniciativaInterna;
	}

	public void setIniciativaInterna(String iniciativaInterna) {
		this.iniciativaInterna = iniciativaInterna;
	}

	public String getSiIniciativaInterna() {
		return siIniciativaInterna;
	}

	public void setSiIniciativaInterna(String siIniciativaInterna) {
		this.siIniciativaInterna = siIniciativaInterna;
	}

	public String getNoIniciativaInterna() {
		return noIniciativaInterna;
	}

	public void setNoIniciativaInterna(String noIniciativaInterna) {
		this.noIniciativaInterna = noIniciativaInterna;
	}

	public Set<PalabraClave> getPalabrasClaves() {
		return palabrasClaves;
	}

	public void setPalabrasClaves(Set<PalabraClave> palabrasClaves) {
		this.palabrasClaves = palabrasClaves;
	}

	public void adicionarPalabraClave(PalabraClave palabra) {
		UtilPalabraClave.limpiaPalabraClave(palabra);
		palabrasClaves.add(palabra);
	}

	public void borrarPalabraClave(PalabraClave palabra) {
		palabrasClaves.remove(palabra);
	}

	public Set<EntidadArticulo> getEntidad() {
		return entidadAval;
	}

	public void setEntidad(Set<EntidadArticulo> entidad) {
		this.entidadAval = entidad;
	}

	public void adicionarEntidad(EntidadArticulo entidad) {
		entidad.setAval(this);
		entidadAval.add(entidad);
	}

	public void borrarEntidad(EntidadArticulo entidad) {
		entidadAval.remove(entidad);
	}

	public Set<EntidadArticulo> getEntidadAval() {
		return entidadAval;
	}

	public void setEntidadAval(Set<EntidadArticulo> entidadAval) {
		this.entidadAval = entidadAval;
	}

	public String getCategoriaConvocatoria() {
		return categoriaConvocatoria;
	}

	public void setCategoriaConvocatoria(String categoriaConvocatoria) {
		this.categoriaConvocatoria = categoriaConvocatoria;
	}

	public String getModalidadLaboratorio() {
		return modalidadLaboratorio;
	}

	public void setModalidadLaboratorio(String modalidadLaboratorio) {
		this.modalidadLaboratorio = modalidadLaboratorio;
	}

	public void adicionarMonto(MontoAno monto) {
		monto.setAval(this);
		montoAval.add(monto);
	}

	public void borrarMonto(MontoAno monto) {
		montoAval.remove(monto);
	}

	public Set<MontoAno> getMontoAval() {
		return montoAval;
	}

	public void setMontoAval(Set<MontoAno> montoAval) {
		this.montoAval = montoAval;
	}

	public void adicionarDependencia(Dependencia dependencia) {
		dependencias.add(dependencia);
	}

	public void borrarDependencia(Dependencia dependencia) {
		dependencias.remove(dependencia);
	}

	public Set<Dependencia> getDependencias() {
		return dependencias;
	}

	public List<Dependencia> getListaDependencias() {
		List<Dependencia> dependencias = new ArrayList<Dependencia>();
		dependencias.addAll(this.dependencias);
		return dependencias;
	}

	public void setDependencias(Set<Dependencia> dependencias) {
		this.dependencias = dependencias;
	}

	public String getOtroLaboratorio() {
		return otroLaboratorio;
	}

	public void setOtroLaboratorio(String otroLaboratorio) {
		this.otroLaboratorio = otroLaboratorio;
	}

	public String getIsocial() {
		return isocial;
	}

	public void setIsocial(String isocial) {
		this.isocial = isocial;
	}

	public Set<PoblacionSolidaria> getPoblacionAval() {
		return poblacionAval;
	}

	public void setPoblacionAval(Set<PoblacionSolidaria> poblacionAval) {
		this.poblacionAval = poblacionAval;
	}

	public void adicionarPoblacion(PoblacionSolidaria poblacion) {
		poblacion.setAval(this);
		poblacionAval.add(poblacion);
	}

	public void borrarPoblacion(PoblacionSolidaria poblacion) {
		poblacionAval.remove(poblacion);
	}

	public String getUab() {
		return uab;
	}

	public void setUab(String uab) {
		this.uab = uab;
	}

	public Long getIdProyecto() {
		return idProyecto;
	}

	public void setIdProyecto(Long idProyecto) {
		this.idProyecto = idProyecto;
	}

	public String getNombreProyecto() {
		return nombreProyecto;
	}

	public void setNombreProyecto(String nombreProyecto) {
		this.nombreProyecto = nombreProyecto;
	}

	public String getTipoEvento() {
		return tipoEvento;
	}

	public void setTipoEvento(String tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	public String getModalidad() {
		return modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}

	public String getMecanismo() {
		return mecanismo;
	}

	public void setMecanismo(String mecanismo) {
		this.mecanismo = mecanismo;
	}

	public double getDuracion() {
		return duracion;
	}

	public void setDuracion(double duracion) {
		this.duracion = duracion;
	}

	public double getDuracions() {
		return duracions;
	}

	public void setDuracions(double duracions) {
		this.duracions = duracions;
	}

	public double getDuraciond() {
		return duraciond;
	}

	public void setDuraciond(double duraciond) {
		this.duraciond = duraciond;
	}

	public double getDuracionh() {
		return duracionh;
	}

	public void setDuracionh(double duracionh) {
		this.duracionh = duracionh;
	}

	public Long getValorPersonalTotal() {
		return valorPersonalTotal;
	}

	public void setValorPersonalTotal(Long valorPersonalTotal) {
		this.valorPersonalTotal = valorPersonalTotal;
	}

	public String getCategoriaGPI() {
		return categoriaGPI;
	}

	public void setCategoriaGPI(String categoriaGPI) {
		this.categoriaGPI = categoriaGPI;
	}

	public String getSubCategoriaGPI() {
		return subCategoriaGPI;
	}

	public void setSubCategoriaGPI(String subCategoriaGPI) {
		this.subCategoriaGPI = subCategoriaGPI;
	}

	public String getTecnologia() {
		return tecnologia;
	}

	public void setTecnologia(String tecnologia) {
		this.tecnologia = tecnologia;
	}

	public String getDescripcionTecnologia() {
		return descripcionTecnologia;
	}

	public void setDescripcionTecnologia(String descripcionTecnologia) {
		this.descripcionTecnologia = descripcionTecnologia;
	}

	public String getEstadoDesarrollo() {
		return estadoDesarrollo;
	}

	public void setEstadoDesarrollo(String estadoDesarrollo) {
		this.estadoDesarrollo = estadoDesarrollo;
	}

	public String getSustitutos() {
		return sustitutos;
	}

	public void setSustitutos(String sustitutos) {
		this.sustitutos = sustitutos;
	}

	public String getPerfilesClientes() {
		return perfilesClientes;
	}

	public void setPerfilesClientes(String perfilesClientes) {
		this.perfilesClientes = perfilesClientes;
	}

	public String getAliados() {
		return aliados;
	}

	public void setAliados(String aliados) {
		this.aliados = aliados;
	}

	public Date getAviFechaPublicacionResult() {
		return aviFechaPublicacionResult;
	}

	public void setAviFechaPublicacionResult(Date aviFechaPublicacionResult) {
		this.aviFechaPublicacionResult = aviFechaPublicacionResult;
	}

	public Long getNoExpediente() {
		return noExpediente;
	}

	public void setNoExpediente(Long noExpediente) {
		this.noExpediente = noExpediente;
	}

	public void setCreadorId(String creadorId) {
		this.creadorId = creadorId;
	}

	public String getCreadorId() {
		return creadorId;
	}

	public void setCreadorDocumento(String creadorDocumento) {
		this.creadorDocumento = creadorDocumento;
	}

	public String getCreadorDocumento() {
		return creadorDocumento;
	}

	public Long getMontoEntidadCoejecutora() {
		return montoEntidadCoejecutora;
	}

	public void setMontoEntidadCoejecutora(Long montoEntidadCoejecutora) {
		this.montoEntidadCoejecutora = montoEntidadCoejecutora;
	}

	// INICIO AVAL MOVILIDADES

	public String getParticipanteMovilidad() {
		return participanteMovilidad;
	}

	public void setParticipanteMovilidad(String participanteMovilidad) {
		this.participanteMovilidad = participanteMovilidad;
	}

	public String getTituloTrabajoMovilidad() {
		return tituloTrabajoMovilidad;
	}

	public void setTituloTrabajoMovilidad(String tituloTrabajoMovilidad) {
		this.tituloTrabajoMovilidad = tituloTrabajoMovilidad;
	}

	public String getInstitucionMovilidad() {
		return institucionMovilidad;
	}

	public void setInstitucionMovilidad(String institucionMovilidad) {
		this.institucionMovilidad = institucionMovilidad;
	}

	public String getInstitucionCoorgMovilidad() {
		return institucionCoorgMovilidad;
	}

	public void setInstitucionCoorgMovilidad(String institucionCoorgMovilidad) {
		this.institucionCoorgMovilidad = institucionCoorgMovilidad;
	}

	public String getLugarMovilidad() {
		return lugarMovilidad;
	}

	public void setLugarMovilidad(String lugarMovilidad) {
		this.lugarMovilidad = lugarMovilidad;
	}

	public String getDuracionMovilidad() {
		return duracionMovilidad;
	}

	public void setDuracionMovilidad(String duracionMovilidad) {
		this.duracionMovilidad = duracionMovilidad;
	}

	public String getTematicaFRedes() {
		return tematicaFRedes;
	}

	public void setTematicaFRedes(String tematicaFRedes) {
		this.tematicaFRedes = tematicaFRedes;
	}

	public void adicionarResultado(ResultadoAval resultado) {
		resultado.setAval(this);
		resultados.add(resultado);
	}

	public void borrarResultado(ResultadoAval resultado) {
		resultados.remove(resultado);
	}

	public List<ResultadoAval> getListaResultados() {
		List<ResultadoAval> listaResultados = new ArrayList<ResultadoAval>();
		listaResultados.addAll(resultados);
		return listaResultados;
	}

	public Set<ResultadoAval> getResultados() {
		return resultados;
	}

	public void setResultados(Set<ResultadoAval> resultados) {
		this.resultados = resultados;
	}

	public String getAportaRecursosPropios() {
		return aportaRecursosPropios;
	}

	public void setAportaRecursosPropios(String aportaRecursosPropios) {
		this.aportaRecursosPropios = aportaRecursosPropios;
	}

	// FIN AVAL MOVILIDADES

	public String getNombreGrupoPINV() {
		return nombreGrupoPINV;
	}

	public void setNombreGrupoPINV(String nombreGrupoPINV) {
		this.nombreGrupoPINV = nombreGrupoPINV;
	}

	public List<MontoAno> getListaMontos() {
		List<MontoAno> list = new ArrayList<MontoAno>();
		list.addAll(montoAval);
		return list;
	}

	public String getResponsableCambio() {
		return responsableCambio;
	}

	public void setResponsableCambio(String responsableCambio) {
		this.responsableCambio = responsableCambio;
	}

	public Set<AvalActividad> getActividadAval() {
		return actividadAval;
	}

	public void setActividadAval(Set<AvalActividad> actividadAval) {
		this.actividadAval = actividadAval;
	}

	public void eliminarActividad(AvalActividad actividad) {
		actividadAval.remove(actividad);
	}

	public void adicionarActividad(AvalActividad actividad) {
		actividad.setAval(this);
		actividadAval.add(actividad);
	}

	public Long getMontoEspecieEntidadCoejecutora() {
		return montoEspecieEntidadCoejecutora;
	}

	public void setMontoEspecieEntidadCoejecutora(Long montoEspecieEntidadCoejecutora) {
		this.montoEspecieEntidadCoejecutora = montoEspecieEntidadCoejecutora;
	}

	public Date getFechaUltimoEnvio() {
		return fechaUltimoEnvio;
	}

	public void setFechaUltimoEnvio(Date fechaUltimoEnvio) {
		this.fechaUltimoEnvio = fechaUltimoEnvio;
	}

	public String getConsideracionesEticas() {
		return consideracionesEticas;
	}

	public void setConsideracionesEticas(String consideracionesEticas) {
		this.consideracionesEticas = consideracionesEticas;
	}

	public String getModalidadPropiedadIntelectual() {
		return modalidadPropiedadIntelectual;
	}

	public void setModalidadPropiedadIntelectual(String modalidadPropiedadIntelectual) {
		this.modalidadPropiedadIntelectual = modalidadPropiedadIntelectual;
	}

	public Long getAvalRelacionado() {
		return avalRelacionado;
	}

	public void setAvalRelacionado(Long avalRelacionado) {
		this.avalRelacionado = avalRelacionado;
	}

	public Convenio getConvenio() {
		return convenio;
	}

	public void setConvenio(Convenio convenio) {
		this.convenio = convenio;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aviId == null) ? 0 : aviId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Aval other = (Aval) obj;
		if (aviId == null) {
			if (other.aviId != null)
				return false;
		} else if (!aviId.equals(other.aviId))
			return false;
		return true;
	}

	public String getTextoVicerrectoria() {
		return textoVicerrectoria;
	}

	public void setTextoVicerrectoria(String textoVicerrectoria) {
		this.textoVicerrectoria = textoVicerrectoria;
	}

	public Date getAviFechaAvalVice() {
		return aviFechaAvalVice;
	}

	public void setAviFechaAvalVice(Date aviFechaAvalVice) {
		this.aviFechaAvalVice = aviFechaAvalVice;
	}

	public String getInterSedes() {
		return interSedes;
	}

	public void setInterSedes(String interSedes) {
		this.interSedes = interSedes;
	}

	public String getDependenciaContrapartida() {
		return dependenciaContrapartida;
	}

	public void setDependenciaContrapartida(String dependenciaContrapartida) {
		this.dependenciaContrapartida = dependenciaContrapartida;
	}

	public Long getTerminos() {
		return terminos;
	}

	public void setTerminos(Long terminos) {
		this.terminos = terminos;
	}

	public String getAviAvalUab() {
		return aviAvalUab;
	}

	public void setAviAvalUab(String aviAvalUab) {
		this.aviAvalUab = aviAvalUab;
	}

	public String getComentariosUab() {
		return comentariosUab;
	}

	public void setComentariosUab(String comentariosUab) {
		this.comentariosUab = comentariosUab;
	}

	public Date getAviFechaAvalUab() {
		return aviFechaAvalUab;
	}

	public void setAviFechaAvalUab(Date aviFechaAvalUab) {
		this.aviFechaAvalUab = aviFechaAvalUab;
	}

	public boolean isEsGrupoInvestigacion() {
		if (this.tipo != null && this.tipo.equals(TIPO_GRUPO_INVESTIGACION)) {
			return true;
		}
		return false;
	}

	public boolean isEsInvestigadorIndependiente() {
		if (this.tipo != null && this.tipo.equals(TIPO_INVESTIGADOR_INDEPENDIENTE)) {
			return true;
		}
		return false;
	}

	public boolean isEsCentroInvestigacion() {
		if (this.tipo != null && this.tipo.equals(TIPO_CENTRO_INVESTIGACION)) {
			return true;
		}
		return false;
	}

	public boolean isEsJornadaDocente() {
		if (this.tipo != null && this.tipo.equals(TIPO_JORNADA_DOCENTE)) {
			return true;
		}
		return false;
	}

	public boolean isEsProyectoInvestigacion() {
		if (this.tipo != null && this.tipo.equals(TIPO_INVESTIGACION)) {
			return true;
		}
		return false;
	}

	public boolean isEsRegalias() {
		if (this.tipo != null && this.tipo.equals(TIPO_REGALIAS)) {
			return true;
		}
		return false;
	}
	
	public boolean isEsConvocatoriaRegalias() {
		if (this.tipo != null && this.tipo.equals(TIPO_CONVOCATORIA_REGALIAS)) {
			return true;
		}
		return false;
	}
	
	public boolean isEsRequisitosRegalias() {
		if (this.tipo != null && this.tipo.equals(TIPO_REGALIAS_VERIF_REQ)) {
			return true;
		}
		return false;
	}

	public boolean isEsMovilidadEvento() {
		if (this.tipo != null && this.tipo.equals(TIPO_MOVILIDAD)) {
			return true;
		}
		return false;
	}
	
	public boolean isEsLaboratoriosCentrosInstitutos() {
		if (this.tipo != null && this.tipo.equals(TIPO_CENTRO_INVESTIGACION)) {
			return true;
		}
		return false;
	}
	
	public boolean isEsEtico() {
		if (this.tipo != null && this.tipo.equals(TIPO_ETICO))
			return true;
		return false;
	}
	
	public boolean isEsArticuloInvestigacion() {
		if (this.tipo != null && this.tipo.equals(TIPO_ARTICULO_INVESTIGACION))
			return true;
		return false;
	}
	
	public boolean isTieneRecurso() {
		if (this.avalTieneRecurso != null && this.avalTieneRecurso.equals("SI"))
			return true;
		return false;
	}

	public boolean isEsInterSedes() {
		if (this.interSedes != null && "S".equals(this.interSedes)) {
			return true;
		}
		return false;
	}

	public boolean isEsProyectoContrapartida() {
		if (this.tipo != null && this.tipo.equals(TIPO_INVESTIGACION_CONT)) {
			return true;
		}
		return false;
	}

	public boolean isEsContrapartidaFacultad() {
		if (this.dependenciaContrapartida != null && "F".equals(this.dependenciaContrapartida)) {
			return true;
		}
		return false;
	}

	public boolean isEsPaedRegalias() {
		if (this.tipo != null && this.tipo.equals(TIPO_PAED_REGALIAS)) {
			return true;
		}
		return false;
	}

	public boolean isEsRegaliasVicerrectoria() {
		if (isEsRegalias() && this.interSedes != null && "S".equals(this.interSedes)) {
			return true;
		}
		return false;
	}

	public boolean isEsPaedRegaliasVicerrectoria() {
		if (isEsPaedRegalias() && this.interSedes != null && "S".equals(this.interSedes)) {
			return true;
		}
		return false;
	}
	
	public boolean isEsConvocatoriaRegaliasVicerrectoria() {
		if (isEsConvocatoriaRegalias() && this.interSedes != null && "S".equals(this.interSedes)) {
			return true;
		}
		return false;
	}

	public boolean isEsAvalAprobadoParaLegalizacion() {
		return (StringUtils.isNotBlank(this.getAviEstado()) && StringUtils.isNotBlank(this.getAviAvaldireccion())
				&& ((this.getAviEstado().equals(Aval.REVISADO_DIRECCION)
						&& this.getAviAvaldireccion().equals(Aval.APROBADO))
				|| (this.getAviEstado().equals(Aval.REVISADO_VICERRECTORIA)
						&& this.getAviAvaldireccion().equals(Aval.APROBADO))
				|| (this.getAviEstado().equals(Aval.REVISADO_DRE) && this.getAvalDRE().equals(Aval.APROBADO))
				|| (this.getAviEstado().equals(Aval.REVISADO_RECTORIA) && this.getAvalRectoria().equals(Aval.APROBADO))));
	}
	

	public String getTieneArchivosSoporteParticipacionConvocatoria() {
		return tieneArchivosSoporteParticipacionConvocatoria;
	}

	public void setTieneArchivosSoporteParticipacionConvocatoria(String tieneArchivosSoporteParticipacionConvocatoria) {
		this.tieneArchivosSoporteParticipacionConvocatoria = tieneArchivosSoporteParticipacionConvocatoria;
	}

	public String getTieneConvocatoriaProyecto() {
		return tieneConvocatoriaProyecto;
	}

	public void setTieneConvocatoriaProyecto(String tieneConvocatoriaProyecto) {
		this.tieneConvocatoriaProyecto = tieneConvocatoriaProyecto;
	}

	public String getEntidadTerritorialProyectoRegalidas() {
		return entidadTerritorialProyectoRegalidas;
	}

	public void setEntidadTerritorialProyectoRegalidas(String entidadTerritorialProyectoRegalidas) {
		this.entidadTerritorialProyectoRegalidas = entidadTerritorialProyectoRegalidas;
	}

	public String getEsAvalParaRevisionSede() {
		return esAvalParaRevisionSede;
	}

	public void setEsAvalParaRevisionSede(String esAvalParaRevisionSede) {
		this.esAvalParaRevisionSede = esAvalParaRevisionSede;
	}

	public String getEsAvalParaRevisionVice() {
		return (esAvalParaRevisionVice == null) ? "" : esAvalParaRevisionVice;
	}

	public void setEsAvalParaRevisionVice(String esAvalParaRevisionVice) {
		this.esAvalParaRevisionVice = esAvalParaRevisionVice;
	}

	public String getTipoAvalCIN() {
		return tipoAvalCIN;
	}

	public void setTipoAvalCIN(String tipoAvalCIN) {
		this.tipoAvalCIN = tipoAvalCIN;
	}

	public String getEsAvalParaRevisionDRE() {
		return esAvalParaRevisionDRE==null ? "N": esAvalParaRevisionDRE;
	}

	public void setEsAvalParaRevisionDRE(String esAvalParaRevisionDRE) {
		this.esAvalParaRevisionDRE = esAvalParaRevisionDRE;
	}

	public String getAvalDRE() {
		return avalDRE;
	}

	public void setAvalDRE(String esAvalDRE) {
		this.avalDRE = esAvalDRE;
	}

	public String getTextoDRE() {
		return textoDRE;
	}

	public void setTextoDRE(String textoDRE) {
		this.textoDRE = textoDRE;
	}

	public Date getFechaAvalDRE() {
		return fechaAvalDRE;
	}

	public void setFechaAvalDRE(Date fechaAvalDRE) {
		this.fechaAvalDRE = fechaAvalDRE;
	}

	public AvalComiteEtica getCepi() {
		return cepi;
	}

	public void setCepi(AvalComiteEtica cepi) {
		this.cepi = cepi;
	}

	public String getAviNaturalezaConvocatoria() {
		return aviNaturalezaConvocatoria;
	}

	public void setAviNaturalezaConvocatoria(String aviNaturalezaConvocatoria) {
		this.aviNaturalezaConvocatoria = aviNaturalezaConvocatoria;
	}

	public String getAvalCEPI() {
		return avalCEPI;
	}

	public void setAvalCEPI(String avalCEPI) {
		this.avalCEPI = avalCEPI;
	}

	public String getTextoCEPI() {
		return textoCEPI;
	}

	public void setTextoCEPI(String textoCEPI) {
		this.textoCEPI = textoCEPI;
	}

	public Date getFechaAvalCEPI() {
		return fechaAvalCEPI;
	}

	public void setFechaAvalCEPI(Date fechaAvalCEPI) {
		this.fechaAvalCEPI = fechaAvalCEPI;
	}

	public String getAvalCESI() {
		return avalCESI;
	}

	public void setAvalCESI(String avalCESI) {
		this.avalCESI = avalCESI;
	}

	public String getTextoCESI() {
		return textoCESI;
	}

	public void setTextoCESI(String textoCESI) {
		this.textoCESI = textoCESI;
	}

	public Date getFechaAvalCESI() {
		return fechaAvalCESI;
	}

	public void setFechaAvalCESI(Date fechaAvalCESI) {
		this.fechaAvalCESI = fechaAvalCESI;
	}

	public String getAvalTieneRecurso() {
		return avalTieneRecurso;
	}

	public void setAvalTieneRecurso(String avalTieneRecurso) {
		this.avalTieneRecurso = avalTieneRecurso;
	}

	public Tipos getTipoRecursoAvalEtico() {
		return tipoRecursoAvalEtico;
	}

	public void setTipoRecursoAvalEtico(Tipos tipoRecursoAvalEtico) {
		this.tipoRecursoAvalEtico = tipoRecursoAvalEtico;
	}

	public Date getFechaRecurso() {
		return fechaRecurso;
	}

	public void setFechaRecurso(Date fechaRecurso) {
		this.fechaRecurso = fechaRecurso;
	}

	public String getAvalCEPIRecurso() {
		return avalCEPIRecurso;
	}

	public void setAvalCEPIRecurso(String avalCEPIRecurso) {
		this.avalCEPIRecurso = avalCEPIRecurso;
	}

	public Date getFechaAvalCEPIRecurso() {
		return fechaAvalCEPIRecurso;
	}

	public void setFechaAvalCEPIRecurso(Date fechaAvalCEPIRecurso) {
		this.fechaAvalCEPIRecurso = fechaAvalCEPIRecurso;
	}

	public String getAvalTieneQueja() {
		return avalTieneQueja;
	}

	public void setAvalTieneQueja(String avalTieneQueja) {
		this.avalTieneQueja = avalTieneQueja;
	}

	public Date getFechaQueja() {
		return fechaQueja;
	}

	public void setFechaQueja(Date fechaQueja) {
		this.fechaQueja = fechaQueja;
	}

	public String getAvalCESIQueja() {
		return avalCESIQueja;
	}

	public void setAvalCESIQueja(String avalCESIQueja) {
		this.avalCESIQueja = avalCESIQueja;
	}

	public String getTextoCESIQueja() {
		return textoCESIQueja;
	}

	public void setTextoCESIQueja(String textoCESIQueja) {
		this.textoCESIQueja = textoCESIQueja;
	}

	public Date getFechaCESIQueja() {
		return fechaCESIQueja;
	}

	public void setFechaCESIQueja(Date fechaCESIQueja) {
		this.fechaCESIQueja = fechaCESIQueja;
	}

	public String getTextoRecurso() {
		return textoRecurso;
	}

	public void setTextoRecurso(String textoRecurso) {
		this.textoRecurso = textoRecurso;
	}

	public String getTextoQueja() {
		return textoQueja;
	}

	public void setTextoQueja(String textoQueja) {
		this.textoQueja = textoQueja;
	}

	public String getAvalArticuloTitulo() {
		return avalArticuloTitulo;
	}

	public void setAvalArticuloTitulo(String avalArticuloTitulo) {
		this.avalArticuloTitulo = avalArticuloTitulo;
	}

	public Tipos getAvalArticuloEstado() {
		return avalArticuloEstado;
	}

	public void setAvalArticuloEstado(Tipos avalArticuloEstado) {
		this.avalArticuloEstado = avalArticuloEstado;
	}

	public String getAvalArticuloResumen() {
		return avalArticuloResumen;
	}

	public void setAvalArticuloResumen(String avalArticuloResumen) {
		this.avalArticuloResumen = avalArticuloResumen;
	}

	public String getAvalArticuloRevista() {
		return avalArticuloRevista;
	}

	public void setAvalArticuloRevista(String avalArticuloRevista) {
		this.avalArticuloRevista = avalArticuloRevista;
	}

	public String getAvalArticuloObjetivo() {
		return avalArticuloObjetivo;
	}

	public void setAvalArticuloObjetivo(String avalArticuloObjetivo) {
		this.avalArticuloObjetivo = avalArticuloObjetivo;
	}
	
	public String getAvalRectoria() {
		return avalRectoria;
	}

	public void setAvalRectoria(String avalRectoria) {
		this.avalRectoria = avalRectoria;
	}

	public String getTextoRectoria() {
		return textoRectoria;
	}

	public void setTextoRectoria(String textoRectoria) {
		this.textoRectoria = textoRectoria;
	}

	public Date getFechaAvalRectoria() {
		return fechaAvalRectoria;
	}

	public void setFechaAvalRectoria(Date fechaAvalRectoria) {
		this.fechaAvalRectoria = fechaAvalRectoria;
	}

	public Set<AvalSubTipos> getSubTipoEspecificaciones() {
		return subTipoEspecificaciones;
	}

	public void setSubTipoEspecificaciones(Set<AvalSubTipos> subTipoEspecificaciones) {
		this.subTipoEspecificaciones = subTipoEspecificaciones;
	}
	
    public void adicionarSubTipoEspecificacion(AvalSubTipos nom) {
        nom.setAval(this);
        subTipoEspecificaciones.add(nom);
    }

    public void borrarSubTipoEspecificacion(AvalSubTipos nom) {
    	subTipoEspecificaciones.remove(nom);
    }

    public ArrayList<AvalSubTipos> getListaSubTiposEspecificacion() {
        ArrayList<AvalSubTipos> listaSubTipos = new ArrayList<AvalSubTipos>();
        listaSubTipos.addAll(subTipoEspecificaciones);
        return listaSubTipos;
    }

	public String getCodigoMinciencias() {
		return codigoMinciencias;
	}

	public void setCodigoMinciencias(String codigoMinciencias) {
		this.codigoMinciencias = codigoMinciencias;
	}
	
}