sizemin_campo_default=1
noExisteNumDoc=El n\u00FAmero de documento ingresado no se encuentra en el sistema.
okAdInvestigadorProyeto=Se adicion\u00F3 exitosamente al proyecto\:
noAdInvestigadorProyecto=imposible adicionar el investigador
ok_lineasAdicionadas=Se adicionaron satisfactoriamente las l\u00EDneas\:
no_lineasAdicionadas=No se adicionaron nuevas l\u00EDneas
lineasNoEncontradas=No se encontraron lineas por\:
proponer_nueva_linea=Si desea proponer una nueva linea de investigaci\u00F3n haga clik
ingreseNombreNuevaLineaAProponer=L\u00EDnea a proponer
ingresoPalabraBusquedaLineas=Tenga en cuenta las opciones con/sin t\u00EDlde en la b\u00FAsqueda.
tituloSubseccionAdicionLineas=Adici\u00F3n de L\u00EDneas
personaAdicionarEsEstudiante=Esta persona es un estudiante, al adicionarlo lo convertir\u00E1 en investigador.
investigadorYaestaAdicionado=Este investigador ya ha sido adicionado al proyecto\:
NoLineaPropuesta=No pudo proponerse la L\u00EDnea\:
sizemin_campo_default_mov=2
